//! Versioned, neutral rendering seam. This command never writes, installs,
//! downloads, loads private preferences, or creates a consumer arete.toml.
//! The caller owns source resolution, Git hygiene and transactional application.

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use anyhow::{bail, Context, Result};
use clap::Args;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use super::{jsonc::JsonDoc, mcp_config, skills, Env};

const IDS: [&str; 5] = ["codex", "claude-code", "opencode", "oh-my-pi", "cursor"];

#[derive(Debug, Args)]
pub struct WorkspaceArgs {
    /// Print protocol capabilities without reading a request or project.
    #[arg(long, conflicts_with = "request")]
    pub protocol_info: bool,
    /// JSON request generated by an explicit local workspace orchestrator.
    #[arg(long, required_unless_present = "protocol_info")]
    pub request: Option<PathBuf>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Request {
    pub schema_version: u32,
    pub target: PathBuf,
    pub harnesses: Vec<String>,
    pub skills: Vec<Skill>,
    pub mcp: BTreeMap<String, Server>,
    pub instructions: String,
    #[serde(default)]
    pub existing: BTreeMap<String, Existing>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Skill {
    pub name: String,
    pub source: PathBuf,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "transport", rename_all = "snake_case", deny_unknown_fields)]
pub enum Server {
    Stdio { command: PathBuf, args: Vec<String> },
    Http { url: String },
}

#[derive(Debug, Default, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Existing {
    pub content: String,
    #[serde(default)]
    pub owned_entries: BTreeMap<String, Value>,
}

#[derive(Debug, Serialize)]
pub struct File {
    pub path: String,
    pub content: String,
    /// Only MCP entries in a shared file are owned; other keys are the user's.
    pub owned_entries: Option<BTreeMap<String, Value>>,
}

#[derive(Debug, Serialize)]
pub struct Copy {
    pub source: PathBuf,
    pub path: String,
}

#[derive(Debug, Serialize)]
pub struct Rendered {
    pub schema_version: u32,
    pub files: Vec<File>,
    pub copies: Vec<Copy>,
    pub instruction_reference: Option<String>,
    pub activation: BTreeMap<String, String>,
}

fn identifier(value: &str) -> Result<()> {
    if value.is_empty()
        || value.len() > 100
        || !value
            .bytes()
            .all(|c| c.is_ascii_alphanumeric() || b"-_".contains(&c))
    {
        bail!("invalid logical name");
    }
    Ok(())
}

fn entry(id: &str, server: &Server) -> Result<Value> {
    // Reuse the public adapter's field/transport shapes with explicit inputs.
    let mut value = match server {
        Server::Stdio { command, args } => {
            if !command.is_absolute() || args.iter().any(|arg| arg.contains('\0')) {
                bail!("stdio requires an explicit executable path and valid arguments");
            }
            let command = command.to_str().context("non-UTF8 executable path")?;
            let mut value = mcp_config::shape(id, command, false).arete;
            if id == "opencode" {
                value["command"] = json!(std::iter::once(command.to_string())
                    .chain(args.iter().cloned())
                    .collect::<Vec<_>>());
            } else {
                value["args"] = json!(args);
            }
            value
        }
        Server::Http { url } => {
            let parsed = url::Url::parse(url).context("invalid MCP URL")?;
            if !["https", "http"].contains(&parsed.scheme())
                || !parsed.username().is_empty()
                || parsed.password().is_some()
                || parsed.query().is_some()
                || parsed.fragment().is_some()
            {
                bail!("MCP URL cannot contain credentials, query parameters or fragments");
            }
            let mut value = mcp_config::shape(id, "", false).docs;
            value["url"] = json!(url);
            value
        }
    };
    // Context and environment forwarding are handled by the supplied local
    // executable wrapper, avoiding incompatible native env interpolation rules.
    if id == "oh-my-pi" {
        value["enabled"] = json!(true);
    }
    Ok(value)
}

fn current(
    format: mcp_config::Format,
    content: &str,
    top: &str,
    name: &str,
) -> Result<Option<Value>> {
    match format {
        mcp_config::Format::Json => Ok(JsonDoc::parse(content)?.get(&[top, name])),
        mcp_config::Format::Toml => {
            let doc: toml::Value = toml::from_str(content).context("invalid TOML")?;
            Ok(doc
                .get(top)
                .and_then(|v| v.get(name))
                .map(serde_json::to_value)
                .transpose()?)
        }
        mcp_config::Format::Yaml => bail!("unsupported workspace configuration format"),
    }
}

pub fn render(request: Request) -> Result<Rendered> {
    if request.schema_version != 1 || !request.target.is_absolute() {
        bail!("unsupported workspace-agent request");
    }
    let selected: BTreeSet<_> = request.harnesses.iter().map(String::as_str).collect();
    if selected.len() != request.harnesses.len() || selected.iter().any(|id| !IDS.contains(id)) {
        bail!("unknown or duplicate harness");
    }
    let mut names = BTreeSet::new();
    for skill in &request.skills {
        identifier(&skill.name)?;
        if !names.insert(skill.name.to_lowercase()) || !skill.source.is_absolute() {
            bail!("duplicate skill name or non-absolute local source");
        }
    }
    for name in request.mcp.keys() {
        identifier(name)?;
    }
    let env = Env {
        root: request.target.clone(),
        home: None,
        vars: BTreeMap::new(),
    };
    let mut result = Rendered {
        schema_version: 1,
        files: Vec::new(),
        copies: Vec::new(),
        instruction_reference: None,
        activation: BTreeMap::new(),
    };
    let mut copies = BTreeSet::new();
    for id in IDS {
        let mcp_config::Placement::File { path, format } =
            mcp_config::placement(&env, id, mcp_config::Scope::Project)?
        else {
            bail!("missing project configuration placement");
        };
        let relative = path
            .strip_prefix(&request.target)?
            .to_str()
            .context("invalid output path")?
            .to_string();
        let existing = request.existing.get(&relative);
        let enabled = selected.contains(id);
        let top = mcp_config::shape(id, "", false).top_key;
        let desired: BTreeMap<String, Value> = if enabled {
            request
                .mcp
                .iter()
                .map(|(name, server)| Ok((name.clone(), entry(id, server)?)))
                .collect::<Result<_>>()?
        } else {
            BTreeMap::new()
        };
        let mut remove = Vec::new();
        if let Some(existing) = existing {
            for (name, old) in &existing.owned_entries {
                if current(format, &existing.content, top, name)?.as_ref() != Some(old) {
                    bail!("modified managed MCP entry in {relative}");
                }
                if !desired.contains_key(name) {
                    remove.push(name.clone());
                }
            }
            for (name, desired) in &desired {
                if let Some(value) = current(format, &existing.content, top, name)? {
                    if !existing.owned_entries.contains_key(name) && &value != desired {
                        bail!("unowned MCP entry collision in {relative}");
                    }
                    // Even identical user entries remain unowned. Avoid silently
                    // adopting them and deleting them on a future deselection.
                    if !existing.owned_entries.contains_key(name) {
                        bail!("existing MCP entry requires explicit adoption in {relative}");
                    }
                }
            }
        }
        if !desired.is_empty() || !remove.is_empty() {
            result.files.push(File {
                path: relative,
                content: mcp_config::render_entries(
                    format,
                    existing.map(|v| v.content.as_str()),
                    top,
                    &desired,
                    &remove,
                    false,
                )?,
                owned_entries: Some(desired),
            });
        }
        if !enabled {
            continue;
        }
        let dir = if ["codex", "opencode"].contains(&id) {
            request.target.join(".agents/skills")
        } else {
            skills::skill_dirs(&env, id, false)
                .into_iter()
                .next()
                .context("missing skill placement")?
        };
        for skill in &request.skills {
            let path = dir
                .join(&skill.name)
                .strip_prefix(&request.target)?
                .to_str()
                .context("invalid skill path")?
                .to_string();
            if copies.insert(path.clone()) {
                result.copies.push(Copy {
                    source: skill.source.clone(),
                    path,
                });
            }
        }
        match id {
            "claude-code" => result.files.push(File {
                path: ".claude/rules/arete-workspace.md".into(),
                content: request.instructions.clone(),
                owned_entries: None,
            }),
            "cursor" => result.files.push(File {
                path: ".cursor/rules/arete-workspace.mdc".into(),
                content: format!(
                    "---\ndescription: Local workspace navigation\nalwaysApply: true\n---\n{}",
                    request.instructions
                ),
                owned_entries: None,
            }),
            _ => {
                result.instruction_reference = Some(".arete-agent/CONTEXT.md".into());
            }
        }
        result.activation.insert(
            id.into(),
            match id {
                "codex" => "project_trust_required",
                "claude-code" => "project_mcp_approval_required",
                "cursor" => "native_activation_required",
                _ => "native_probe_required",
            }
            .into(),
        );
    }
    if !selected.is_empty() {
        result.files.push(File {
            path: ".arete-agent/CONTEXT.md".into(),
            content: request.instructions,
            owned_entries: None,
        });
    }
    Ok(result)
}

pub fn run(args: WorkspaceArgs) -> Result<()> {
    let value = if args.protocol_info {
        json!({"schema_version":1,"request_schema":[1],"harnesses":IDS,"mode":"render_only","engine_version":env!("CARGO_PKG_VERSION")})
    } else {
        let path = args.request.context("request required")?;
        let metadata = std::fs::symlink_metadata(&path)?;
        if !metadata.is_file() || metadata.len() > 4 * 1024 * 1024 {
            bail!("request must be a bounded regular file");
        }
        let request: Request = serde_json::from_slice(&std::fs::read(path)?)
            .context("invalid workspace-agent request")?;
        serde_json::to_value(render(request)?)?
    };
    println!("{}", serde_json::to_string(&value)?);
    Ok(())
}
